### ISSUE TITLE
[Feature Request] Support more formats and hosts

### ISSUE THREAD

**Issue by cole-h** [manojkarthick/reddsaver#10]
It would be nice to be able to save videos posted to reddit in the form of `.gifv` or `.mp4`, or those uploaded to gfycat and imgur (in those formats).

**Comment by manojkarthick** [comment]
Thanks @cole-h - I am working on GIF and video download support as well, hope to get it done by next release.

**Comment by manojkarthick** [comment]
@cole-h The `v0.3.0` release adds support for GIFs from Imgur, Gfycat, Giphy, etc. See [README](https://github.com/manojkarthick/reddsaver/blob/master/README.md) for more details. Hope this helps!
