### ISSUE TITLE
[feature request] Interactive request for credentials

### ISSUE THREAD

**Issue by cole-h** [manojkarthick/reddsaver#15]
I'd really like to not have my password in plaintext on my disk. It would be great if I could do one of the following:

1) get prompted for my password and TOTP code (and maybe even username) at runtime
2) set a command to get my password (e.g. for use with https://www.passwordstore.org/) and TOTP code

----

Somewhat-related:

Passwords may contain the `:` character, so I don't think that's a good separator for the PASSWORD env var. Maybe a separate TOTP env var should be used?

**Comment by manojkarthick** [comment]
@cole-h The username and password just need to be present in the environment to be picked up by reddsaver. So, you could omit username and password from `.env` file. You can use an external script or a tool like [direnv](https://direnv.net/) to set the username, password by running a command. As long as it is present in the environment, it should be picked up.

With regards to the `:` delimiter: that is a Reddit API setting, so I'm afraid it's something that's out of my control.

**Comment by cole-h** [comment]
Ah, I was under the impression it only wanted to read from a `.env` file. That makes sense. I can do that, thanks!

**Comment by manojkarthick** [comment]
> Ah, I was under the impression it only wanted to read from a `.env` file. That makes sense. I can do that, thanks!

Great. Please file an issue in case you encounter any problems. You can use the `reddsaver --show-config` command to check if the variables are picked up properly.

**Comment by cole-h** [comment]
Since TOTP changes so frequently, I had to run reddsaver with `direnv exec . cargo run --release -- [args]` which works a charm (otherwise, I'd have to `cd ..` and `cd -`, or `direnv reload` first). Thanks for reminding me of something so obvious!

**Comment by manojkarthick** [comment]
> Since TOTP changes so frequently, I had to run reddsaver with `direnv exec . cargo run -- [args]` which works a charm (otherwise, I'd have to `cd ..` and `cd -`, or `direnv reload` first). Thanks for reminding me of something so obvious!

Great! Just wanted to leave a reminder to use `--release` profile for `cargo run` to run the optimized artifact (Not sure if you're using that already)

**Comment by cole-h** [comment]
Yep, thanks, I left that out of my hand-typed command line :P

(Though I did run it in debug mode a few times -- speed wasn't that bad for me)

**Comment by manojkarthick** [comment]
Awesome! Running the release binary makes a huge difference compared to the debug binary for me.
