### ISSUE TITLE
[Feature request] Functionality to save upvoted posts.

### ISSUE THREAD

**Issue by pxssy** [manojkarthick/reddsaver#20]
Same thing you've done with saved posts, but this time with user-upvoted posts. With comments is possible. I heard some talk about unsaving downloading, possible to do it here as well?

Many thanks.

**Comment by manojkarthick** [comment]
Thanks @pxssy - it should be possible to do the same for upvoted posts. Will try to add this feature in the next release.

**Comment by manojkarthick** [comment]
@pxssy The latest release [v0.3.2](https://github.com/manojkarthick/reddsaver/releases/tag/v0.3.2) now supports downloading media from upvoted posts using the `--upvoted` flag.
