### ISSUE TITLE
[Feature Request] Option to change output format

### ISSUE THREAD

**Issue by bytestrike** [manojkarthick/reddsaver#25]
by default the script will put all saved media in folders according to their subreddit.
I'm not really interested in this folder structure, as i only have a huge image dump. Would it be possible to change the output format to different folder-structures/ no folder structes at all?

(awesome script btw)

**Comment by manojkarthick** [comment]
There's no capability for configuring the folder structure (or no folders) at the moment. If you're just looking to unnest into a single directory, you could use something like this on linux/mac: `find <data_directory> -mindepth 2 -type f -exec mv -i '{}' <target_dictionary> ';'`. I _might_ add similar functionality in a later release depending on whether there's more people asking for something like this.
