### ISSUE TITLE
Missing field: "access_token"

### ISSUE THREAD

**Issue by guenter-r** [manojkarthick/reddsaver#42]
When running the script
`reddsaver -e reddsaver.env -d .`

it immediately interrupts because of the following error:

`Error: ReqwestError(reqwest::Error { kind: Decode, source: Error("missing field `access_token`", line: 1, column: 95) })`

Any ideas where this is coming from? I have no knowledge of Rust, but tried to find where the error might be, could not find a way to resolve.. thanks a lot

**Comment by szerencl** [comment]
Make sure all env variables are filled out correctly in reddsaver.env https://github.com/manojkarthick/reddsaver/issues/2#issuecomment-753711896.
And if you're on linux don't forget to `unset USERNAME`.
This solved the issue for me.

**Comment by guenter-r** [comment]
I selected the wrong application type on reddit in the settings.
Web app != script .... thanks anyways
