### ISSUE TITLE
App creating sub-directories with underlined filenames

### ISSUE THREAD

**Issue by CitronSorcier** [manojkarthick/reddsaver#5]
I installed the 2.2 binaries and ran the app, and downloaded the files in a new folder for a quick comparison with the files downloaded using the previous version. I've found two probably undesired behaviours, one of them I'm reporting on this ticket: when reddsaver tries to download files whose post titles contain underlines, a new sub-directory (sometimes 2 nested sub-directories) are created, like this (download directory is ./folders_02):

  ~/reddsaver 2.2/folders_02/osr/face_folio_|_a_little_preview_of_some_concept_sketches_(100_pc/underlined_filename.jpg

The files end up in the nested sub-directory, though.

**Comment by manojkarthick** [comment]
Thanks for raising this issue. Would you be able to share the link to the Reddit post corresponding to the file name you’ve shared? This would help with reproducing the bug and testing the (future) fixes.

**Comment by CitronSorcier** [comment]
Here it is:
https://www.reddit.com/r/osr/comments/k5zeyi/face_folio_a_little_preview_of_some_concept/

Guess the underlines are not related to this bug, the original title "Face Folio | a little preview of some concept sketches (100 PC/NPC portraits for your RPG game; Zine Quest 2)" has no underlines..

**Comment by manojkarthick** [comment]
I think the issue is because of / in the post’s title. I’ll verify this and if so it should be an easy fix

**Comment by manojkarthick** [comment]
@CitronSorcier I've release v0.2.3 with fixes for #6 and #7  - please check if the issues you encountered are resolved when you get a chance.
