### ISSUE TITLE
Multi-image posts not being downloaded

### ISSUE THREAD

**Issue by CitronSorcier** [manojkarthick/reddsaver#6]
Beginning on 2.2 (running binaries) with human-readable option active, reddsaver is no longer downloading all the images in multi-image posts, just one for each post.

**Comment by manojkarthick** [comment]
Thanks for raising the issue. I have identified the cause of the issue and am already working on a bug fix. Until then please continue using without the human readable flag as the issue is not present when using that option as per my testing.
